# Generated by Django 4.0.1 on 2022-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usrs_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrs',
            name='idDM',
            field=models.IntegerField(),
        ),
    ]
